In [3]:
import numpy as np

In [5]:
import pandas as pd

In [7]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [8]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [9]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
credits.head(1)['crew'].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "depart

In [13]:
movies.shape

(4803, 20)

In [17]:
credits.shape

(4803, 4)

In [19]:
movies = movies.merge(credits,on='title')

In [21]:
movies.shape

(4809, 23)

In [23]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [27]:
#genres
#id
#keywords
#title
#overview
#cast
#crew


movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [31]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [33]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [35]:
movies.dropna(inplace=True)

In [37]:
movies.duplicated().sum()

0

In [39]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [41]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#[action,adventure,fantasy,scifi

In [43]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
        return L

In [45]:
movies['genres'] = movies['genres'].apply(convert)

In [46]:
movies['genres']

0            [Action]
1         [Adventure]
2            [Action]
3            [Action]
4            [Action]
            ...
4804         [Action]
4805         [Comedy]
4806         [Comedy]
4807             None
4808    [Documentary]
Name: genres, Length: 4806, dtype: object

In [49]:
movies['keywords'] = movies['keywords'].apply(convert)

In [50]:
movies['keywords']

0                      [culture clash]
1                              [ocean]
2                                [spy]
3                          [dc comics]
4                     [based on novel]
                     ...
4804    [united states–mexico barrier]
4805                              None
4806                            [date]
4807                              None
4808                       [obsession]
Name: keywords, Length: 4806, dtype: object

In [51]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",[Action],[culture clash],"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[Adventure],[ocean],"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,[Action],[spy],"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,[Action],[dc comics],"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...",[Action],[based on novel],"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [52]:
movies['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4806, dtype: object

In [56]:
import ast
def convert3(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter = counter+1
        else:
            break
    return L

In [59]:
movies['cast']=movies['cast'].apply(convert3)

In [60]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",[Action],[culture clash],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[Adventure],[ocean],"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,[Action],[spy],"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,[Action],[dc comics],"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...",[Action],[based on novel],"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [61]:
import ast
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
        return L

In [62]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [63]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",[Action],[culture clash],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[Adventure],[ocean],"[Johnny Depp, Orlando Bloom, Keira Knightley]",[]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,[Action],[spy],"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,[Action],[dc comics],"[Christian Bale, Michael Caine, Gary Oldman]",[]
4,49529,John Carter,"John Carter is a war-weary, former military ca...",[Action],[based on novel],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[]

In [64]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [65]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [66]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",[Action],[culture clash],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",[Adventure],[ocean],"[Johnny Depp, Orlando Bloom, Keira Knightley]",[]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",[Action],[spy],"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",[Action],[dc comics],"[Christian Bale, Michael Caine, Gary Oldman]",[]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",[Action],[based on novel],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[]

In [67]:
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "") for i in x])

In [68]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",[Action],[culture clash],"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",[Adventure],[ocean],"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",[Action],[spy],"[DanielCraig, ChristophWaltz, LéaSeydoux]",[]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",[Action],[dc comics],"[ChristianBale, MichaelCaine, GaryOldman]",[]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",[Action],[based on novel],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[]

In [69]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [70]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",[Action],[culture clash],"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",[Adventure],[ocean],"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",[Action],[spy],"[DanielCraig, ChristophWaltz, LéaSeydoux]",[],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",[Action],[dc comics],"[ChristianBale, MichaelCaine, GaryOldman]",[],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",[Action],[based on novel],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[],"[John, Carter, is, a, war-weary,, former, mili..."

In [71]:
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'culture clash',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver']

In [72]:
new_df = movies[['movie_id','title','tags']]

In [73]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,NaN
4805,72766,Newlyweds,NaN
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,NaN
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [74]:
new_df['tags'] = new_df['tags'].astype(str)

C:\Users\Krishna Kumar\AppData\Local\Temp\ipykernel_13080\3365301815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].astype(str)

In [75]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"['In', 'the', '22nd', 'century,', 'a', 'parapl..."
1,285,Pirates of the Caribbean: At World's End,"['Captain', 'Barbossa,', 'long', 'believed', '..."
2,206647,Spectre,"['A', 'cryptic', 'message', 'from', 'Bond’s', ..."
3,49026,The Dark Knight Rises,"['Following', 'the', 'death', 'of', 'District'..."
4,49529,John Carter,"['John', 'Carter', 'is', 'a', 'war-weary,', 'f..."

In [76]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Krishna Kumar\AppData\Local\Temp\ipykernel_13080\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [77]:
new_df

,movie_id,title,tags
0,19995,Avatar,"['in', 'the', '22nd', 'century,', 'a', 'parapl..."
1,285,Pirates of the Caribbean: At World's End,"['captain', 'barbossa,', 'long', 'believed', '..."
2,206647,Spectre,"['a', 'cryptic', 'message', 'from', 'bond’s', ..."
3,49026,The Dark Knight Rises,"['following', 'the', 'death', 'of', 'district'..."
4,49529,John Carter,"['john', 'carter', 'is', 'a', 'war-weary,', 'f..."
...,...,...,...
4804,9367,El Mariachi,nan
4805,72766,Newlyweds,nan
4806,231617,"Signed, Sealed, Delivered","['""signed,', 'sealed,', 'delivered""', 'introdu..."
4807,126186,Shanghai Calling,nan
4808,25975,My Date with Drew,"['ever', 'since', 'the', 'second', 'grade', 'w..."

In [78]:
new_df['tags'][0]

"['in', 'the', '22nd', 'century,', 'a', 'paraplegic', 'marine', 'is', 'dispatched', 'to', 'the', 'moon', 'pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.', 'action', 'culture clash', 'samworthington', 'zoesaldana', 'sigourneyweaver']"

In [79]:
new_df['tags'][1]

"['captain', 'barbossa,', 'long', 'believed', 'to', 'be', 'dead,', 'has', 'come', 'back', 'to', 'life', 'and', 'is', 'headed', 'to', 'the', 'edge', 'of', 'the', 'earth', 'with', 'will', 'turner', 'and', 'elizabeth', 'swann.', 'but', 'nothing', 'is', 'quite', 'as', 'it', 'seems.', 'adventure', 'ocean', 'johnnydepp', 'orlandobloom', 'keiraknightley']"

In [80]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [81]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [82]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [83]:
import nltk

In [84]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [85]:
ps.stem(' ')

' '

In [86]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
        return " ".join(y)

In [87]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Krishna Kumar\AppData\Local\Temp\ipykernel_13080\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [88]:
new_df

      movie_id                                     title           tags
0        19995                                    Avatar         ['in',
1          285  Pirates of the Caribbean: At World's End    ['captain',
2       206647                                   Spectre          ['a',
3        49026                     The Dark Knight Rises  ['following',
4        49529                               John Carter       ['john',
...        ...                                       ...            ...
4804      9367                               El Mariachi            nan
4805     72766                                 Newlyweds            nan
4806    231617                 Signed, Sealed, Delivered   ['"signed,',
4807    126186                          Shanghai Calling            nan
4808     25975                         My Date with Drew       ['ever',

[4806 rows x 3 columns]

In [89]:
from sklearn.metrics.pairwise import cosine_similarity

In [90]:
similarity = cosine_similarity(vectors)

In [91]:
similarity[2]

array([0.04588315, 0.        , 1.        , ..., 0.03333333, 0.        ,
       0.        ])

In [92]:
sorted(similarity[0],reverse = True)

[0.9999999999999997,
 0.23179316248638268,
 0.17292861596651865,
 0.16222142113076252,
 0.15511334686589623,
 0.14350946197048195,
 0.14350946197048195,
 0.1404878717372541,
 0.13834289277321493,
 0.13497638119975425,
 0.13497638119975425,
 0.13245323570650439,
 0.12780429685269148,
 0.12725695259515554,
 0.12725695259515554,
 0.12565617248750865,
 0.12373764497794919,
 0.12262786789699316,
 0.11980845957463077,
 0.11946953821789978,
 0.11846977555181845,
 0.11846977555181845,
 0.11846977555181845,
 0.11803342130469503,
 0.11803342130469503,
 0.11749469908920933,
 0.11633501014942217,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528086,
 0.11470786693528086,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11128297681493143,
 0.11020775375559674,
 0.10882143751650174,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10748615458500278,
 0.10526315789473682,
 0.10526315789473682,
 0.10457739712320041,
 0.10259783520851541,
 0.1025978352085154,
 0.1025978352085154,
 0.10147651372376074,
 0.10012523486435176,
 0.10012523486435176,
 0.0993399267798783,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09733285267845751,
 0.09733285267845751,
 0.09733285267845751,
 0.09567297464698797,
 0.09567297464698797,
 0.09567297464698797,
 0.0936585811581694,
 0.0936585811581694,
 0.09365858115816939,
 0.09197090092274487,
 0.0917662935482247,
 0.0917662935482247,
 0.0917662935482247,
 0.0899842541331695,
 0.0899842541331695,
 0.0899842541331695,
 0.0899842541331695,
 0.0899842541331695,
 0.08913130356431727,
 0.08830215713766958,
 0.08830215713766958,
 0.08830215713766958,
 0.08830215713766958,
 0.08830215713766958,
 0.08671099695241198,
 0.08671099695241198,
 0.08671099695241198,
 0.08671099695241198,
 0.08603090020146065,
 0.08520286456846099,
 0.08520286456846099,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.08308129847945278,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08240856434303291,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07755667343294811,
 0.07755667343294811,
 0.07743385993795009,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07443229275647868,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.06997114285413195,
 0.06997114285413195,
 0.06997114285413195,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06839855680567694,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06622661785325219,
 0.06554735253444621,
 0.06554735253444621,
 0.06554735253444621,
 0.064888568452305,
 0.06424925662032355,
 0.06424925662032355,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06302534916632545,
 0.06302534916632545,
 0.06243905410544626,
 0.06243905410544626,
 0.06243905410544626,
 0.061868822488974594,
 0.061868822488974594,
 0.061868822488974594,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06077371254627639,
 0.06024752331287778,
 0.06024752331287778,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.059234887775909226,
 0.058271654674806495,
 0.057807331301607985,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.057353933467640436,
 0.056055185467121044,
 0.056055185467121044,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05564148840746572,
 0.05484084971070817,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05407380704358751,
 0.05298129428260174,
 0.05298129428260174,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.05263157894736841,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.0512989176042577,
 0.05098127419345816,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.05006261743217588,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.04891159880445184,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.047836487323493986,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.0468292905790847,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04588314677411235,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.04499212706658475,
 0.044356912218772235,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04415107856883479,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.04335549847620599,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.042601432284230495,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.04188539082916955,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.041204282171516456,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.04055535528269063,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03993615319154359,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03934447376823168,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03877833671647406,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03823595564509362,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03771571432023571,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03721614637823934,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03673591791853225,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03582871819500093,
 0.03582871819500093,
 0.03582871819500093,
 0.03582871819500093,
 0.03582871819500093,
 0.03582871819500093,
 0.03582871819500093,
 0.03582871819500093,
 0.03582871819500093,
 0.03582871819500093,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03539961627023943,
 0.03498557142706597,
 0.03498557142706597,
 0.03498557142706597,
 0.03498557142706597,
 0.03498557142706597,
 0.03498557142706597,
 0.03498557142706597,
 0.03498557142706597,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03458572319330373,
 0.03419927840283847,
 0.03419927840283847,
 0.03419927840283847,
 0.03419927840283847,
 0.03419927840283847,
 0.03419927840283847,
 0.03419927840283847,
 0.03419927840283847,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03382550457458691,
 0.03346372407051273,
 0.03346372407051273,
 0.03346372407051273,
 0.03346372407051273,
 0.03346372407051273,
 0.03346372407051273,
 0.03346372407051273,
 0.033113308926626096,
 0.033113308926626096,
 0.033113308926626096,
 0.033113308926626096,
 0.033113308926626096,
 0.033113308926626096,
 0.033113308926626096,
 0.033113308926626096,
 0.032773676267223106,
 0.032773676267223106,
 0.032773676267223106,
 0.032773676267223106,
 0.032773676267223106,
 0.0324442842261525,
 0.0324442842261525,
 0.0324442842261525,
 0.0324442842261525,
 0.0324442842261525,
 0.0324442842261525,
 0.0324442842261525,
 0.032124628310161774,
 0.032124628310161774,
 0.032124628310161774,
 0.032124628310161774,
 0.032124628310161774,
 0.032124628310161774,
 0.032124628310161774,
 0.032124628310161774,
 0.032124628310161774,
 0.031814238148788886,
 0.031814238148788886,
 0.031814238148788886,
 0.031814238148788886,
 0.031814238148788886,
 0.031814238148788886,
 0.031512674583162724,
 0.031512674583162724,
 0.031512674583162724,
 0.03121952705272313,
 0.03121952705272313,
 0.03121952705272313,
 0.03121952705272313,
 0.03121952705272313,
 0.030934411244487297,
 0.03065696697424829,
 0.03065696697424829,
 0.03065696697424829,
 0.03065696697424829,
 0.030386856273138196,
 0.030386856273138196,
 0.03012376165643889,
 0.03012376165643889,
 0.029617443887954613,
 0.029617443887954613,
 0.029373674772302332,
 0.029373674772302332,
 0.029135827337403247,
 0.029135827337403247,
 0.029135827337403247,
 0.028903665650803993,
 0.028903665650803993,
 0.02845551966122361,
 0.02845551966122361,
 0.028239124736245246,
 0.028239124736245246,
 0.028239124736245246,
 0.028027592733560522,
 0.028027592733560522,
 0.028027592733560522,
 0.02782074420373286,
 0.02782074420373286,
 0.027420424855354085,
 0.027036903521793755,
 0.026851080677052733,
 0.026851080677052733,
 0.02649064714130087,
 0.026315789473684206,
 0.026315789473684206,
 0.02597621667330655,
 0.02518164825829395,
 0.02503130871608794,
 0.02459594839716409,
 0.02459594839716409,
 0.02459594839716409,

In [96]:
def recommend(movie):
    movie_index = new_df[new_df['title']== movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse = True, key = lambda x:x[1])[1:6]
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [97]:
recommend('Avatar')

Apollo 18
Tears of the Sun
Beowulf
The Adventures of Pluto Nash
The Book of Life

In [98]:
new_df[new_df['title']=="Batman Begins"].index[0]

119

In [99]:
sorted(list(enumerate(similarity[0])),reverse = True, key = lambda x:x[1])[1:6]

[(3606, 0.23179316248638268),
 (529, 0.17292861596651865),
 (151, 0.16222142113076252),
 (311, 0.15511334686589623),
 (942, 0.14350946197048195)]

In [100]:
import pickle

In [101]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl', 'wb'))

In [102]:
new_df

      movie_id                                     title           tags
0        19995                                    Avatar         ['in',
1          285  Pirates of the Caribbean: At World's End    ['captain',
2       206647                                   Spectre          ['a',
3        49026                     The Dark Knight Rises  ['following',
4        49529                               John Carter       ['john',
...        ...                                       ...            ...
4804      9367                               El Mariachi            nan
4805     72766                                 Newlyweds            nan
4806    231617                 Signed, Sealed, Delivered   ['"signed,',
4807    126186                          Shanghai Calling            nan
4808     25975                         My Date with Drew       ['ever',

[4806 rows x 3 columns]

In [103]:
pickle.dump(similarity,open('similarity.pkl','wb'))